apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: control-plane
  namespace: argocd
spec:
  description: Control plane applications
  sourceRepos:
    - https://github.com/mrmime123/Devops-showcase-repo.git
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'