replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

postgresql:
  enabled: true
  postgresqlUsername: user
  postgresqlPassword: password
  postgresqlDatabase: database
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard"
  service:
    port: 5432

postgresqlHA:
  enabled: false
  replicas: 3
  persistence:
    enabled: true
    size: 8Gi
    storageClass: "standard"
  service:
    port: 5432