apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: control-plane
  source:
    repoURL: https://argoproj.github.io/argo-Helm
    chart: argo-workflows
    targetRevision: 0.45.19
    helm:
      valuesObject:
        controller:
          parallelism: 10
          resourceRateLimit:
            limit: 5
            burst: 1
          workflowDefaults:
            spec:
              serviceAccountName: argo-workflows-sa
              ttlStrategy:
                secondsAfterCompletion: 86400
              nodeSelector:
                cloud.google.com/gke-spot: "true"
          nodeSelector:
            cloud.google.com/gke-spot: "true"
        server:
          nodeSelector:
            cloud.google.com/gke-spot: "true"
          ingress:
            enabled: true
            ingressClassName: private-nginx
            hosts:
              - host: argo-workflows.example.com
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
