apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  project: control-plane
  source:
    repoURL: https://argoproj.github.io/argo-Helm
    chart: argo-events
    targetRevision: 2.4.16
    helm:

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true