# Backend argocd application with helm
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  project: control-plane
  source:
    repoURL: 'https://github.com/your-repo/backend'
    targetRevision: HEAD
    path: helm/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true