apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: control-plane
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 1.20.0
    helm:
      valuesObject:
        nodeSelector:
          cloud.google.com/gke-spot: "true"
        metrics:
          enabled: true
        rbacManager:
          nodeSelector:
            cloud.google.com/gke-spot: "true"
        replicas: 1
        args:
          - --sync-interval=10m
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true